Mark https://www.sec.tu-bs.de/~danarp/drebin/ as dead
https://www.sec.tu-bs.de/~danarp/drebin/ SSL validation fails due to
server not returning the full certificate chain.

```
> Issues
   1. https://www.sec.tu-bs.de/~danarp/drebin/ - error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (unable to get local issuer certificate) - README.md - L259
Error: Process completed with exit code 1.
```

Ref: https://github.com/ashishb/android-security-awesome/actions/runs/5759618894/job/15614033663